- name: Check that variables root_email_address is defined
  assert:
    that:
      - root_email_address is defined
    msg: "Define variable root_email_address !"

- name: Set Origins-Pattern
  blockinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    insertafter: "Unattended-Upgrade::Origins-Pattern {"
    block: "{{ origin_patterns }}"

- name: "Set root mail alias"
    lineinfile:
      path: /etc/aliases
      regexp: "^root:"
      line: "root: {{ root_email_address }}"
    notify: "run newaliases"
