- name: Check that variables root_email_address is defined
  assert:
    that:
      - root_email_address is defined
    msg: "Define variable root_email_address !"

- name: Set Origins-Pattern
  blockinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    insertafter: "Unattended-Upgrade::Origins-Pattern {"
    block: "{{ unattended_upgrades_origin_patterns }}"

- name: Set Package-Blacklist
  blockinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    insertafter: "Unattended-Upgrade::Package-Blacklist {"
    marker: "# {mark} ANSIBLE MANAGED Blacklist"
    block: "{{ unattended_upgrades_blacklist }}"

- name: Set Automatic-Reboot
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: 'Unattended-Upgrade::Automatic-Reboot "'
    line:   'Unattended-Upgrade::Automatic-Reboot "{{ unattended_upgrades_automatic_reboot }}";'

- name: Set Automatic-Reboot-Time
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: 'Unattended-Upgrade::Automatic-Reboot-Time "'
    line:   'Unattended-Upgrade::Automatic-Reboot-Time "{{ unattended_upgrades_automatic_reboot_time }}";'

- name: "Set root mail alias"
  lineinfile:
    path: /etc/aliases
    regexp: "^root:"
    line: "root: {{ root_email_address }}"
  notify: "run newaliases"
