---
- name: Require Debian
  assert:
    that:
      - ansible_distribution == "Debian"
    msg: "Only Debian is supported, this is {{ ansible_distribution }}"

- name: Does not work on Ansible 2.8
  assert:
    that:
      - ansible_version is defined
      - ansible_version.full is version('2.8', '<') or ansible_version.full is version('2.9', '>=')
    msg: "Ansible 2.8 has broken package_facts, see https://github.com/ansible/ansible/issues/56921"

- name: Install unattended-upgrades package
  package:
    name: unattended-upgrades

- name: Enable periodic updates
  copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    src: /usr/share/unattended-upgrades/20auto-upgrades
    remote_src: yes

- name: Set Mail to root
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: 'Unattended-Upgrade::Mail "'
    line:   'Unattended-Upgrade::Mail "root";'

- name: Set MailOnlyOnError
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: 'Unattended-Upgrade::MailOnlyOnError "'
    line:   'Unattended-Upgrade::MailOnlyOnError "true";'

- name: get package facts
  package_facts:

- name: is MTA installed?
  set_fact:
    mta_installed: "{{ 'sendmail' in ansible_facts.packages or 'exim4-base' in ansible_facts.packages or 'postfix' in ansible_facts.packages }}"

- name: Install sendmail package if no MTA is installed
  package:
    name: sendmail
    state: present
  when: not mta_installed

- name: Install mailutils package
  package:
    name: mailutils
    state: present