---
- name: "require Debian"
  assert:
    that:
      - ansible_facts['distribution'] == "Debian"
    fail_msg: "Only Debian is supported, this is {{ ansible_facts['distribution'] }}"
    quiet: true

- name: "install unattended-upgrades package"
  package:
    name: unattended-upgrades

- name: "enable periodic updates"
  copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    src: /usr/share/unattended-upgrades/20auto-upgrades
    remote_src: yes
    force: false

- name: "check existence of mail commands"
  when: unattended_upgrades_enable_mailing
  block:
    # see https://www.debian.org/doc/debian-policy/ch-customized-programs.html#s-mail-transport-agents
    - name: "check existence of /usr/sbin/sendmail"
      stat:
        path: /usr/sbin/sendmail
      register: p

    - name: "warn if /usr/sbin/sendmail is missing"
      ansible.builtin.assert:
        that:
          - p.stat.exists
        fail_msg: "WARNING: /usr/sbin/sendmail is missing! Unattended-upgrades won't send emails until 'sendmail', 'msmtp-mta' or 'postfix' is installed!"
        quiet: true
      ignore_errors: true

    # unattended-upgrades tries first sendmail, then mail command
    # see https://github.com/mvo5/unattended-upgrades/blob/2.9/unattended-upgrade#L1508
    - name: "check existence of /usr/bin/mail"
      stat:
        path: /usr/bin/mail
      register: p

    - name: "warn if /usr/bin/mail is missing"
      ansible.builtin.assert:
        that:
          - p.stat.exists
        fail_msg: "WARNING: /usr/bin/mail is missing! Unattended-upgrades won't send emails until 'mailutils' or 'bsd-mailx' is installed!"
        quiet: true
      ignore_errors: true
