- name: "check that variables root_email_address is defined"
  assert:
    that:
      - root_email_address is defined
    msg: "Define variable root_email_address !"
    quiet: true

# see the script /usr/lib/apt/apt.systemd.daily for options

- name: "set APT::Periodic::Update-Package-Lists"
  lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: 'APT::Periodic::Update-Package-Lists "'
    line:   'APT::Periodic::Update-Package-Lists "always";'

- name: "set APT::Periodic::Unattended-Upgrade"
  lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: 'APT::Periodic::Unattended-Upgrade "'
    line:   'APT::Periodic::Unattended-Upgrade "always";'

- name: "set Unattended-Upgrade::Origins-Pattern"
  blockinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    insertafter: "Unattended-Upgrade::Origins-Pattern {"
    block: "{{ unattended_upgrades_origin_patterns }}"

- name: "set Unattended-Upgrade::Package-Blacklist"
  blockinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    insertafter: "Unattended-Upgrade::Package-Blacklist {"
    marker: "# {mark} ANSIBLE MANAGED Blacklist"
    block: "{{ unattended_upgrades_blacklist }}"

- name: "set Unattended-Upgrade::Automatic-Reboot"
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: 'Unattended-Upgrade::Automatic-Reboot "'
    line:   'Unattended-Upgrade::Automatic-Reboot "{{ unattended_upgrades_automatic_reboot }}";'

- name: "set Unattended-Upgrade::Automatic-Reboot-Time"
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: 'Unattended-Upgrade::Automatic-Reboot-Time "'
    line:   'Unattended-Upgrade::Automatic-Reboot-Time "{{ unattended_upgrades_automatic_reboot_time }}";'

# TODO - probably remove it once we deploy it everywhere
- name: "remove legacy option Unattended-Upgrade::MailOnlyOnError"
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: 'Unattended-Upgrade::MailOnlyOnError "'
    state: absent

- name: "configure unattended-upgrades to send emails"
  when: unattended_upgrades_enable_mailing
  block:
    - name: "set Unattended-Upgrade::Mail to 'root'"
      lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: 'Unattended-Upgrade::Mail "'
        line:   'Unattended-Upgrade::Mail "root";'

    - name: "set Unattended-Upgrade::MailReport to 'only-on-error'"
      lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: 'Unattended-Upgrade::MailReport "'
        line:   'Unattended-Upgrade::MailReport "only-on-error";'

    - name: "set root mail alias"
      lineinfile:
        state: present
        path: /etc/aliases
        create: true
        owner: root
        group: root
        mode: '0644'
        regexp: "^root:"
        line: "root: {{ root_email_address }}"
      notify: "run newaliases"

- name: "configure unattended-upgrades to not send emails"
  when: not unattended_upgrades_enable_mailing
  block:
    - name: "unset Unattended-Upgrade::Mail"
      lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: 'Unattended-Upgrade::Mail "'
        line:   '// Unattended-Upgrade::Mail "root";'

    - name: "unset Unattended-Upgrade::MailReport"
      lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: 'Unattended-Upgrade::MailReport "'
        line:   '// Unattended-Upgrade::MailReport "only-on-error";'
